
package ws_generated.shopInfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShopInfoService", targetNamespace = "http://sellmegood.com", wsdlLocation = "http://vladislav-laptop:8080/sell_me_good_war_exploded/ShopInfoService?wsdl")
public class ShopInfoService
    extends Service
{

    private final static URL SHOPINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHOPINFOSERVICE_EXCEPTION;
    private final static QName SHOPINFOSERVICE_QNAME = new QName("http://sellmegood.com", "ShopInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://vladislav-laptop:8080/sell_me_good_war_exploded/ShopInfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHOPINFOSERVICE_WSDL_LOCATION = url;
        SHOPINFOSERVICE_EXCEPTION = e;
    }

    public ShopInfoService() {
        super(__getWsdlLocation(), SHOPINFOSERVICE_QNAME);
    }

    public ShopInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHOPINFOSERVICE_QNAME, features);
    }

    public ShopInfoService(URL wsdlLocation) {
        super(wsdlLocation, SHOPINFOSERVICE_QNAME);
    }

    public ShopInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHOPINFOSERVICE_QNAME, features);
    }

    public ShopInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShopInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShopInfoImpl
     */
    @WebEndpoint(name = "ShopInfoPort")
    public ShopInfoImpl getShopInfoPort() {
        return super.getPort(new QName("http://sellmegood.com", "ShopInfoPort"), ShopInfoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShopInfoImpl
     */
    @WebEndpoint(name = "ShopInfoPort")
    public ShopInfoImpl getShopInfoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sellmegood.com", "ShopInfoPort"), ShopInfoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHOPINFOSERVICE_EXCEPTION!= null) {
            throw SHOPINFOSERVICE_EXCEPTION;
        }
        return SHOPINFOSERVICE_WSDL_LOCATION;
    }

}
