
package ws_generated.productCatalog;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalogImpl", targetNamespace = "http://sellmegood.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalogImpl {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "get_product_categories")
    @WebResult(name = "category", targetNamespace = "")
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://sellmegood.com", className = "GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://sellmegood.com", className = "GetProductCategoriesResponse")
    @Action(input = "get_product_categories", output = "http://sellmegood.com/ProductCatalogImpl/getProductCategoriesResponse")
    public List<String> getProductCategories();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<Product>
     */
    @WebMethod(action = "get_products_by_category")
    @WebResult(name = "Product", targetNamespace = "")
    @RequestWrapper(localName = "getProductsByCategory", targetNamespace = "http://sellmegood.com", className = "GetProductsByCategory")
    @ResponseWrapper(localName = "getProductsByCategoryResponse", targetNamespace = "http://sellmegood.com", className = "GetProductsByCategoryResponse")
    @Action(input = "get_products_by_category", output = "http://sellmegood.com/ProductCatalogImpl/getProductsByCategoryResponse")
    public List<Product> getProductsByCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(action = "add_product")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://sellmegood.com", className = "AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://sellmegood.com", className = "AddProductResponse")
    @Action(input = "add_product", output = "http://sellmegood.com/ProductCatalogImpl/addProductResponse")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
